# Generated by Django 5.2.12 on 2026-03-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluatorSchedule',
            fields=[
                ('pk', models.CompositePrimaryKey('evaluatorid', 'scheduleid', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Evaluator-Schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MentorSchedule',
            fields=[
                ('pk', models.CompositePrimaryKey('mentorid', 'scheduleid', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Mentor-Schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('day', models.CharField(blank=True, max_length=9, null=True)),
                ('starttime', models.TimeField(blank=True, db_column='startTime', null=True)),
                ('endtime', models.TimeField(blank=True, db_column='endTime', null=True)),
                ('occupied', models.BooleanField(blank=True, null=True)),
                ('state', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Schedule',
                'managed': False,
            },
        ),
    ]
