# Generated by Django 5.2.12 on 2026-03-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Private',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Private',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateEvaluator',
            fields=[
                ('pk', models.CompositePrimaryKey('privateid', 'evaluatorid', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Private-Evaluator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateStudygroup',
            fields=[
                ('pk', models.CompositePrimaryKey('privateid', 'studygroupid', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Private-StudyGroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Terna',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Terna',
                'managed': False,
            },
        ),
    ]
