# Generated by Django 5.2.12 on 2026-03-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('evaluationsperformed', models.IntegerField(blank=True, db_column='evaluationsPerformed', null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('state', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Evaluator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('evaluationsperformed', models.IntegerField(blank=True, db_column='evaluationsPerformed', null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('state', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Mentor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('carne', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('state', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studygroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('approvedgroup', models.BooleanField(blank=True, db_column='approvedGroup', null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('state', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'StudyGroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudygroupStudent',
            fields=[
                ('pk', models.CompositePrimaryKey('studygroupid', 'studentid', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'StudyGroup-Student',
                'managed': False,
            },
        ),
    ]
