# Generated by Django 4.2.30 on 2026-05-08 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'career',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('starthour', models.TimeField(blank=True, null=True)),
                ('endhour', models.TimeField(blank=True, null=True)),
                ('haspayment', models.BooleanField(blank=True, null=True)),
                ('classroom', models.CharField(blank=True, max_length=4, null=True)),
                ('building', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'evaluation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'faculty',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=9, null=True)),
                ('starttime', models.TimeField(blank=True, null=True)),
                ('endtime', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'period',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'speciality',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('est', models.CharField(blank=True, max_length=50, null=True)),
                ('isactive', models.BooleanField(blank=True, null=True)),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orbis_database.career')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orbis_database.faculty')),
            ],
            options={
                'db_table': 'student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('approvedgroup', models.BooleanField(blank=True, null=True)),
                ('isactive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'studygroup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('cat', models.CharField(blank=True, max_length=50, null=True)),
                ('isactive', models.BooleanField(blank=True, null=True)),
                ('evaluationcount', models.IntegerField(blank=True, null=True)),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orbis_database.career')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orbis_database.faculty')),
            ],
            options={
                'db_table': 'teacher',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('evaluationid', models.ForeignKey(blank=True, db_column='evaluationid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orbis_database.evaluation')),
            ],
            options={
                'db_table': 'result',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='evaluation',
            name='studentid',
            field=models.ForeignKey(blank=True, db_column='studentid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orbis_database.student'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='type',
            field=models.ForeignKey(blank=True, db_column='type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orbis_database.type'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orbis_database.career')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orbis_database.faculty')),
            ],
            options={
                'db_table': 'course',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TeachersPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orbis_database.period')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orbis_database.teacher')),
            ],
            options={
                'db_table': 'teachers_period',
                'managed': True,
                'unique_together': {('teacher', 'schedule')},
            },
        ),
        migrations.CreateModel(
            name='StudyGroupTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasaccepted', models.BooleanField(blank=True, null=True)),
                ('studygroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orbis_database.studygroup')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orbis_database.teacher')),
            ],
            options={
                'db_table': 'studygroup_teacher',
                'managed': True,
                'unique_together': {('studygroup', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='StudyGroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haspayment', models.BooleanField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orbis_database.student')),
                ('studygroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orbis_database.studygroup')),
            ],
            options={
                'db_table': 'studygroup_student',
                'managed': True,
                'unique_together': {('studygroup', 'student')},
            },
        ),
        migrations.CreateModel(
            name='SpecialityTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orbis_database.speciality')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orbis_database.teacher')),
            ],
            options={
                'db_table': 'speciality_teacher',
                'managed': True,
                'unique_together': {('teacher', 'area')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orbis_database.evaluation')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orbis_database.teacher')),
            ],
            options={
                'db_table': 'evaluation_teacher',
                'managed': True,
                'unique_together': {('evaluation', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='CourseTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasaccepted', models.BooleanField(blank=True, null=True)),
                ('haspayment', models.BooleanField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orbis_database.course')),
                ('studygroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orbis_database.studygroup')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orbis_database.teacher')),
            ],
            options={
                'db_table': 'course_tutorial',
                'managed': True,
                'unique_together': {('studygroup', 'teacher', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CourseTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orbis_database.course')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orbis_database.teacher')),
            ],
            options={
                'db_table': 'course_teacher',
                'managed': True,
                'unique_together': {('course', 'teacher')},
            },
        ),
    ]
